// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	linebot "github.com/line/line-bot-sdk-go/v7/linebot"
	mock "github.com/stretchr/testify/mock"
)

// ReplyDoer is an autogenerated mock type for the ReplyDoer type
type ReplyDoer struct {
	mock.Mock
}

// Do provides a mock function with given fields:
func (_m *ReplyDoer) Do() (*linebot.BasicResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *linebot.BasicResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*linebot.BasicResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *linebot.BasicResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*linebot.BasicResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReplyDoer creates a new instance of ReplyDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReplyDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReplyDoer {
	mock := &ReplyDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
